config.credits = [
  'Thanks for playing!',
  '',
  '- A Game By Maschinen-Mensch -',
  [
    'Johannes Kristmann - Art & Writing & Design',
    'Riad Djemili - Code & Writing & Design',
  ],
  '',
  '- Additional Content -',
  'Isaac Ashdown - Code',
  'Alexander Batsch - Music & Sounds',
  'Tristan Dahl - Writing & Art',
  'Rafal Fedro - Art',
  'Dennis Kogel - Writing',
  "Octavi 'pixelshuh' Navarro - Art",
  'Almut Schwacke - Sounds',
  'Luke Openshaw - Writing',
  'Yevgeni Pakhmanov - Modding',
  'Nils Ole Timm - Modding',
  '',
  'Funded by Medienboard Berlin-Brandenburg',
  'With Love from Berlin',
  '',
  'BREAK',
  '',
  '',
  '',
  '',
  '-- Texts --',
  '',
  '',
  'TRANSLATION',
  '',
  '-- Special Supporters --',
  '',
  '',
  '[Unit Edition]',
  'Jan David Hassel - Unit: Artist',
  '',
  '[Treasure Edition]',
  'Aaron Carlson - Treasure: Golden Slokra',
  'Benedikt Meyer - Treasure: Golden Beauty',
  '',
  '[Explorer Edition]',
  'David Brender - David Brender the Missionary',
  'Loki Texilake - Loki Texilake the Inventor-Archaeologist',
  'Sebastian Deterding - E.S. Goffterding the Anthropologist',
  "A.G. 'Hami' Hamilton - Sir Deddlee Endeavour the Aviator",
  "Alexander Baisden - Reddick Campbell the Aviator",
  "Alexander Gehlsdorf - Freiherr von Gehlsdorf the Politician",
  "Alison Zawacki - Alison Zawacki the Adventurer",
  "Allison Otting - Allison Otting the Artist",
  "Angel LaBatte - Aeryn the Naturalist",
  "Austin Walker - Austin Walker the Ethnographer",
  "Benedikt Meyer - Benedikt Meyer the Adventurer",
  "Charles E Watkins - Lawrence Talbodd the Wolfman",
  "Christoph Freundl - Christophorus Amiculus the Mathematician",
  "F. Riemschneider - Fridericus Schneider the Inventor",
  "Fabian A. Scherschel - Fabian Aleksandar Scherschel the Journalist",
  "Felix Schulze - Hiram Bingham the Adventurer",
  "G.K. Norman - G.K. Norman the Filmographer",
  "Gloegg - Gloegg the Inventor",
  "Jan David Hassel - Dimir the Cossack",
  "Janne 'Lietu' Enberg - Duke Lietu the Royal Cartographer",
  "Jörg Reisig - Sir Chorge the Pirate",
  "Jörg S. Friedrich - Jörg S. Friedrich the Politician",
  "Kai Kubasta - Kai the Archeologist",
  "Matthew Hadley - Matthew Hadley the Inventor",
  "Matthew Hadley - Matthew Hadley the Inventor",
  "Megan Carnes - Megan Carnes the Composer",
  "Olivia White - Olivia White the Lady of the Night",
  "Patric Mueller - Dingir Bhaak the Inventor",
  "Romain LABROT - Hercule Boumba the Adventurer",
  "Sound of Mystery - Sound of Mystery the Wolfman",
  "Timothy Belli - Tim Belli the Mountain Trooper",
  "Victor G Howard - Baron Victor von Paragon the Naturalist",
  "ZeeZour was here - Zacharias Zour the Scapegrace",
  '',
  '[Fan Edition]',
  "Agerra-T'rel",
  "Aitor Santos",
  "AKiRA",
  "Alexander 'derblaueClaus' Künzle",
  "Alexander Charteris",
  "andilein",
  "angespielt.tv",
  "Arild (Foamed) Iversen",
  "Bernd Schneider",
  "Björn Heinemann",
  "Bram De Keukeleire",
  "Brian Gustafson",
  "Brian Pennington",
  "Brian Rubin",
  "byeow2001",
  "Carsten Behnert",
  "Cedric Suzuki",
  "Chris Botman",
  "Christian-Alexander Dudek",
  "Christopher Hombach",
  "Christopher Stieha",
  "Clara Bennett",
  "Cleroth",
  "Dalibor Frtunik",
  "Daniel & Jessica Boak",
  "Daniel Marx",
  "Daniel Schreiber",
  "Deiss",
  "Dieter Hill",
  "Dominik Marosi",
  "dpeg",
  "Elchus",
  "Fábio 'Otaku Dash' Nunes",
  "Fé Wogan",
  "Felix Grünewald",
  "Florian Stimberg",
  "Florian Wüstholz",
  "Flyingcodfish",
  "Gabriella Dubas",
  "HerrvonSpeck",
  "Ingo Hoffmann",
  "Jake Papas & Elle Begg",
  "JamaicanFlyer",
  "Jan Gauczinski",
  "je8z",
  "João Carlos Bastos",
  "Job van der Zwan",
  "John Leonhart",
  "Jonas Blättermann",
  "Jonathan Gooler",
  "Jussi Pullinen",
  "Kanon",
  "Karen Brigitta Götz",
  "Karin & Florian Lamprecht",
  "Klaus Kling",
  "Kolja Bopp",
  "Kristian J Jaech",
  "Kyle [USER__ERROR] Tejada",
  "L. M. Londo (Eggiwex)",
  "Larissa 'egg head' Kunstel",
  "Luke Openshaw",
  "M. 'Raptor Bait' Schlichting,",
  "Manuel Fa4",
  "Marco Ventilii",
  "Mark Zeman",
  "Markus 'Khaanara' Wolf",
  "Markus Arvidsson",
  "Martin Beierling",
  "Mattias Mikkelä",
  "Michel Wacker",
  "Mike Paquin",
  "Mitchell Roper",
  "Monoxyd Mac Judge",
  "Nicholas Manthey",
  "Niklas 'NigggyEnergy' Meyners",
  "Niklas Meyners",
  "Nikolai Reinke",
  "Oli Wright",
  "Overman",
  "Paul Kamma",
  "Phil Möhler",
  "PV",
  "Ralf C. Adam",
  "Robbie 'EntDem' C",
  "Ryan W Sims",
  "Samuel Vonäsch",
  "Sebastían Kristinsson",
  "Sebastian Ziebell",
  "Seth Work",
  "SheepyTrevor",
  "shockedder",
  "Sturmhard Tempelfeld",
  "THE EXPLORERS CLUB, Norway chapter",
  "Thomas Borreson",
  "Thomas Jansen",
  "Thomas Jeff Mulvany",
  "Troy Hodgkiss",
  "Tuncay",
  "tyrkir",
  "Uke Bosse",  
  '',
  '-- Production Babies --',
  'Willi Janosch - April 19th 2015',
  '',
  '-- Special Thanks --',
  'All our Alpha and Early Access supporters',
  'All our YouTubers and Twitchers',
  'Medienboard Berlin-Brandenburg',
  'Saftladen Games Collective',
  'Happy Tuesday',
  'Lorenzo Pilia',
  'Studio Fizbin',
  'André Bernhard',
  'Ron Gilbert',

  'BREAK',
  'THE END'
]
