config.credits = [
  'Thanks for playing!',
  '',
  '- A Game By Maschinen-Mensch -',
  [
    'Johannes Kristmann - Art & Writing & Design',
    'Riad Djemili - Code & Writing & Design',
  ],
  'Nils Ole Timm - Code',
  '',
  '- Additional Content -',
  'Alexander Batsch - Music',
  'Tristan Dahl - Writing & Art',
  'Rafal Fedro - Art',
  'Dennis Kogel - Writing',
  "Octavi 'pixelshuh' Navarro - Art",
  'Luke Openshaw - Writing',
  'Almut Schwacke - Sounds',
  '',
  'Funded by Medienboard Berlin-Brandenburg',
  'With Love from Berlin',
  '',
  'BREAK',
  '',
  '',
  '',
  '',
  '-- Texts --',
  '',
  '',
  'TRANSLATION',
  '',
  '-- Special Supporters --',
  '',
  '',
  '[Unit Edition]',
  'Jan David Hassel - Unit: Artist',
  '',
  '[Treasure Edition]',
  'Aaron Carlson - Treasure: Golden Slokra',
  'Benedikt Meyer - Treasure: Golden Beauty',
  '',
  '[Explorer Edition]',
  "Kai Kubasta - Kai the Archeologist",
  "Austin Walker - Austin Walker the Ethnographer",
  "Joerg Reisig - Sir Chorge the Pirate",
  "Alison Zawacki - Alison Zawacki the Adventurer",
  'Sebastian Deterding - E.S. Goffterding the Anthropologist',
  'David Brender - David Brender the Missionary',
  'Loki Texilake - Loki Texilake the Inventor-Archaeologist',
  "Gloegg - Gloegg the Inventor",
  "Matthew Hadley - Matthew Hadley the Inventor",
  "A.G. 'Hami' Hamilton - Sir Deddlee Endeavour the Aviator",
  "Victor G Howard - Baron Victor von Paragon the Naturalist",
  "Alexander Gehlsdorf - Freiherr von Gehlsdorf the Politician",
  "Janne 'Lietu' Enberg - Duke Lietu the Royal Cartographer",
  "Olivia White - Olivia White the Lady of the Night",
  "ZeeZour was here - Zacharias Zour the Scapegrace",
  "Matthew Hadley - Matthew Hadley the Inventor",
  "Jan David Hassel - Dimir the Cossack",
  "Alexander Baisden - Reddick Campbell the Aviator",
  "Charles E Watkins - Lawrence Talbodd the Wolfman",
  "Angel LaBatte - Aeryn the Naturalist",
  "Christoph Freundl - Christophorus Amiculus the Mathematician",
  "G.K. Norman - G.K. Norman the Filmographer",
  "F. Riemschneider - Fridericus Schneider the Inventor",
  "Patric Mueller - Dingir Bhaak the Inventor",
  "Timothy Belli - Tim Belli the Mountain Trooper",
  "Fabian A. Scherschel - Fabian Aleksandar Scherschel the Journalist",
  "Megan Carnes - Megan Carnes the Composer",
  "Allison Otting - Allison Otting the Artist",
  "Romain LABROT - Hercule Boumba the Adventurer",
  '',
  '[Fan Edition]',
  'Christian-Alexander Dudek',
  'Thomas Borreson',
  'Jussi Pullinen',
  "Sebastian Ziebell",
  "Florian Stimberg",
  "Manuel Fa4",
  "Job van der Zwan",
  "shockedder",
  "Carsten Behnert",
  "Chris Botman",
  "Arild (Foamed) Iversen",
  "Michel Wacker",
  "Kristian J Jaech",
  "M. 'Raptor Bait' Schlichting",
  "Christopher Hombach",
  "Mark Zeman",
  "Nikolai Reinke",
  "Mattias Mikkelä",
  "Thomas Jeff Mulvany",
  "Kolja Bopp",
  "Kyle Tejada",
  "Paul Kamma",
  "Phil Möhler",
  "Daniel Marx",
  "Alexander Charteris",
  "HerrvonSpeck",
  "Dalibor Frtunik",
  "Aitor Santos",
  "Cedric Suzuki",
  "Markus 'Khaanara' Wolf",
  "Brian Rubin",
  "Sebastían Kristinsson",
  "Cleroth",
  "Overman",
  "Nicholas Manthey",
  "andilein",
  "Jake Papas & Elle Begg",
  "tyrkir",
  "Tuncay",
  "AKiRA",
  "Brian Pennington",
  "Markus Arvidsson",
  "Ralf C. Adam",
  "Niklas 'NigggyEnergy' Meyners",
  "angespielt.tv",
  "Jonas Blättermann",
  "Karin & Florian Lamprecht", 
  "JamaicanFlyer",
  "Florian Wüstholz",
  "Fé Wogan",
  "byeow2001",
  "Jonathan Gooler",
  "Robbie C",
  "Cedric Suzuki",
  "Ryan W Sims",
  "Troy Hodgkiss",
  "Kanon",
  "Fábio 'Otaku Dash' Nunes",
  "Elchus",
  "João Carlos Bastos",
  'Dieter Hill',
  'Uke Bosse',
  'Mike Paquin',
  'John Leonhart',
  "Markus 'Khaanara' Wolf",
  'Sturmhard Tempelfeld',
  'Bram De Keukeleire',
  'Gabriella Dubas',
  "Samuel Vonäsch",
  "Dominik Marosi",
  "Felix Grünewald",
  "Daniel & Jessica Boak",
  "Florian Wüstholz",
  "Agerra-T'rel",
  "Martin Beierling",
  "Jonas Blättermann",
  "Seth Work",
  "Oli Wright",
  "John Leonhart",
  "Luke Openshaw",
  "Fe Wogan",
  "Niklas Meyners",
  "Deiss",
  "Thomas Jansen",
  "Bram De Keukeleire",
  "Jan Gauczinski",
  "Björn Heinemann",
  "PV",
  "Brian Gustafson",
  "Troy Hodgkiss",
  "dpeg",
  "Robbie 'EntDem' C",
  "Mike Paquin",
  "Ingo Hoffmann",
  "Alexander 'derblaueClaus' Künzle",
  "Christopher Stieha",
  '',
  '-- Production Babies --',
  'Willi Janosch - April 19th 2015',
  '',
  '-- Special Thanks --',
  'All our Alpha and Early Access supporters',
  'All our YouTubers and Twitchers',
  'Medienboard Berlin-Brandenburg',
  'Saftladen Games Collective',
  'Happy Tuesday',
  'Lorenzo Pilia',
  'Studio Fizbin',
  'André Bernhard',
  'Ron Gilbert',

  'BREAK',
  'THE END'
]
