config.entities.add([

// pockets

  {
    id: 'pck-dry', 
    name: "txt-pck-dry-name",
    flags: '+jungle',
    previewSprite: 'hud_worldmap_pocketPreview_dry.png',
    slotMarker: 'hud_mapMarker_dry.png',
    ambientSound: 'sfx_loop_dry_1',
    goals: [
      'gol-goldenTemple-moonStone', 
      'gol-goldenTemple-buried'
    ],
    fixtures: [
      [ // resting group
        {ref: 'grp-village'},
        {ref: 'fxt-mission'},
        {ref: 'grp-sanity-nature'},
        {ref: 'grp-sanity-nature'},
        {select:3, group: [
          {ref: 'grp-village'},
          {ref: 'fxt-mission'},
          {ref: 'grp-sanity-nature'},
        ]},
      ],
      [ // loot group
        {ref: 'grp-cave'},
        {ref: 'grp-loot'},
        {ref: 'grp-loot'},
        {ref: 'grp-cave'},
        {ref: 'grp-loot'},
        {ref: 'grp-loot'},
      ],
      [ // utility 
        {ref: 'fxt-stoneCircle'},
        ,
        {ref: 'fxt-shamanHut'},
        {ref: 'fxt-trader'},
      ],
      [ // shrine/special group
        {ref: 'grp-treasure'},
        ,
        {ref: 'grp-treasure'},
        {ref: 'grp-special'},
        {ref: 'grp-treasure'},
        {select:2, group: [
          {ref: 'grp-special'},
          {ref: 'grp-treasure'}
        ]}
      ],
      [
        {reqWorld: '3..', chance:0.5, select:2, ref:'fxt-cave-teleport'}
      ],
      [
        ,
        ,
        {reqDifficulty: '1..', ref: 'fxt-magneticMountain'},
        {reqDifficulty: '1..', ref: 'fxt-magneticMountain'},
        {reqDifficulty: '1..', ref: 'fxt-magneticMountain'},
      ],
      [
        {reqWorld: '3', select: 1, ref: 'fxt-geysir-inactive'},
      ],
      [
        {reqWorld: '4', select: 2, group: [
          {slots: 1, select: 1, ref: 'fxt-volcano-spawn-small-inactive'},
          {slots: 1, select: 1, ref: 'fxt-volcano-spawn-large-inactive'},
          {slots: 3, select: 3, ref: 'fxt-geysir-inactive'},
          {slots: 3, select: 2, ref: 'fxt-geysir-inactive'},
        ]},
      ],
      [
        {reqWorld: '5', select: 1, group: [
          {slots: 1, select: 1, ref: 'fxt-volcano-spawn-large-inactive'},
          {slots: 1, select: 3, ref: 'fxt-volcano-spawn-small-inactive'},
          {slots: 3, select: 4, ref: 'fxt-geysir-inactive'},
        ]},
      ],
      [
        {ref:'fxt-hiddenTreasure'},
        {chance: 0.25, ref:'fxt-mountainFaceSecret'},
      ] 
    ],
    biomes: [
      {select: 1, ref: 'bio-drylands-generic'},
      {select: 1, group: 'grp-grasslands-sanity', chance: 0.1},
      {select: 2, group: 'grp-drylands-sanity'},
      {chance: 0.7, select: 1, reqWorld:'3..', group:[
        {slots: 1, group: 'grp-desert-sanity'},
        {slots: 1, ref: 'bio-drylands-desert'},
      ]},
      {select:2, group: 'grp-drylands-sanity'}
    ]
  },

// biome groups

  {
    id: 'grp-drylands-sanity',
    group: [
      {slots: 1, ref: 'bio-drylands-jungle'},
      {slots: 1, ref: 'bio-drylands-lakes'},
      {slots: 1, ref: 'bio-drylands-stoneForest'},
      {slots: 1, ref: 'bio-drylands-mountains'},
      {slots: 1, ref: 'bio-drylands-pits'},
    ]
  },

// biomes

  {
    id: 'bio-drylands-generic', 
    name: "txt-pck-dry-name",
    flags: '+dry',
    debugColor: 'brown',
    eventImg: {
      day:'evt_bio_drylands_1.png', 
      night:'evt_bio_drylands_1_night.png'
    },
    terrain: [
      {perlin: 0.82,  tile: 'tl-dry'},
      {perlin: 0.79,  tile: 'tl-mountain'},
      {perlin: 0.78,  tile: 'tl-volcano-inactive'},
      {perlin: 0.75,  tile: 'tl-dry'},
      {perlin: 0.70,  tile: 'tl-mountain'},
      {perlin: 0.69,  tile: 'tl-dry-jungle-light'},
      {perlin: 0.68,  tile: 'tl-hill'},
      {perlin: 0.63,  tile: 'tl-dry'},
      {perlin: 0.61,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.58,  tile: 'tl-hill'},
      {perlin: 0.55,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.49,  tile: 'tl-dry-jungle-light'},
      {perlin: 0.47,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.42,  tile: 'tl-dry'},
      {perlin: 0.41,  tile: 'tl-dry-jungle-light'},
      {perlin: 0.39,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.38,  tile: 'tl-dry'},
      {perlin: 0.37,  tile: 'tl-hill'},
      {perlin: 0.35,  tile: 'tl-dry'},
      {perlin: 0.34,  tile: 'tl-mountain'},
      {perlin: 0.30,  tile: 'tl-dry'},
      {perlin: 0.29,  tile: 'tl-volcano-inactive'},
      {perlin: 0.28,  tile: 'tl-mountain'},
      {perlin: 0.22,  tile: 'tl-dry'},
      {perlin: 0.20,  tile: 'tl-mountain'},
      {perlin: 0.17,  tile: 'tl-dry'},
      {perlin: 0.13,  tile: 'tl-dry-jungle-light'},
      {perlin: 0.1,   tile: 'tl-dry-stoneForest'},
      {perlin: 0.0,   tile: 'tl-dry'},
    ],
    fixtures: [
      // {chance: 1.0, select: 1, group: 'grp-sacrileg'},
      // {chance: 1.0, select: 1, group: [
      //   {slots: 1, group: 'grp-utility'},
      //   {slots: 1, group: 'grp-loot'},
      // ]},
      // // Decorative
      // {chance: 1.0, select: 1, group: 'grp-eyeCandy-drylands'},
    ],
    zones: [
      {chance: 1.0, select: 1, group: [
        {slots: 3, ref: 'zn-hyena'},
        {slots: 1, ref: 'zn-tiger'},
        {slots: 1, ref: 'zn-panther'},
      ]},
      {chance: 0.3, select: 1, group: [
        {slots: 3, ref: 'zn-hyena'},
      ]},
      {reqWorld: [2,3], chance: 1.0, select: 1, group: [
        {slots: 1, ref: 'zn-hyena'},
        {slots: 1, ref: 'zn-tiger'},
        {slots: 1, ref: 'zn-panther'},
        {slots: 1, ref: 'zn-giantBird'},
      ]},
      {reqWorld: [4,5], chance: 1.0, select: 1, group: [
        {slots: 1, ref: 'zn-tiger'},
        {slots: 1, ref: 'zn-panther'},
        {slots: 1, ref: 'zn-gorilla'},
        {slots: 2, ref: 'zn-giantBird'},
        {slots: 2, ref: 'zn-raptor'},
      ]},

      {chance: 0.3, ref: 'zn-elephant', select: 1},
    ],
  },
  {
    id: 'bio-drylands-lakes', 
    name: "txt-pck-dry-name",
    flags: '+dry +water',
    debugColor: 'brown',
    eventImg: {
      day:'evt_bio_drylands_1.png', 
      night:'evt_bio_drylands_1_night.png'
    },
    terrain: [
      {perlin: 0.78,  tile: 'tl-river-shallow'},
      {perlin: 0.73,  tile: 'tl-mountain'},
      {perlin: 0.72,  tile: 'tl-volcano-inactive'},
      {perlin: 0.7,   tile: 'tl-mountain'},
      {perlin: 0.695, tile: 'tl-hill'},
      {perlin: 0.63,  tile: 'tl-dry'},
      {perlin: 0.61,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.605, tile: 'tl-hill'},
      {perlin: 0.55,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.51,  tile: 'tl-dry-jungle-light'},
      {perlin: 0.49,  tile: 'tl-river-shallow'},
      {perlin: 0.47,  tile: 'tl-river'},
      {perlin: 0.46,  tile: 'tl-mountain'},
      {perlin: 0.44,  tile: 'tl-river'},
      {perlin: 0.43,  tile: 'tl-river-shallow'},
      {perlin: 0.40,  tile: 'tl-river'},
      {perlin: 0.371, tile: 'tl-dry'},
      {perlin: 0.37,  tile: 'tl-hill'},
      {perlin: 0.30,  tile: 'tl-dry'},
      {perlin: 0.298, tile: 'tl-volcano-inactive'},
      {perlin: 0.28,  tile: 'tl-river-shallow'},
      {perlin: 0.23,  tile: 'tl-river'},
      {perlin: 0.21,  tile: 'tl-mountain'},
      {perlin: 0.18,  tile: 'tl-river'},
      {perlin: 0.16,  tile: 'tl-river-shallow'},
      {perlin: 0.15,  tile: 'tl-mountain'},
      {perlin: 0.12,  tile: 'tl-river'},
      {perlin: 0.1,   tile: 'tl-river-shallow'},
      {perlin: 0.0,   tile: 'tl-dry'},
    ],
    fixtures: [
      // {select: 1, group: 'grp-rest'},
      // {select: 1, group: 'grp-utility'},
      // {select: 1, group: [
      //   {slots: 1, group: 'grp-sacrileg'},
      //   {slots: 1, group: 'grp-loot'},
      // ]},
      // {select: 1, group: 'grp-eyeCandy-drylands'},
    ],
    zones: [
      {chance: 1.0, select: 1, group: [
        {slots: 3, ref: 'zn-hyena'},
        {slots: 1, ref: 'zn-tiger'},
        {slots: 1, ref: 'zn-panther'},
        {slots: 1, ref: 'zn-crocodile'},
      ]},
      {chance: 0.3, select: 1, group: [
        {slots: 3, ref: 'zn-hyena'},
      ]},
      {reqWorld: [2,3], chance: 1.0, select: 1, group: [
        {slots: 1, ref: 'zn-hyena'},
        {slots: 1, ref: 'zn-tiger'},
        {slots: 1, ref: 'zn-panther'},
        {slots: 1, ref: 'zn-crocodile'},
        {slots: 2, ref: 'zn-giantBird'},
        {slots: 1, ref: 'zn-giantCrab'},
      ]},
      {reqWorld: [4,5], chance: 1.0, select: 1, group: [
        {slots: 1, ref: 'zn-tiger'},
        {slots: 1, ref: 'zn-panther'},
        {slots: 1, ref: 'zn-gorilla'},
        {slots: 2, ref: 'zn-giantBird'},
        {slots: 2, ref: 'zn-giantCrab'},
        {slots: 2, ref: 'zn-raptor'},
      ]},

      {chance: 0.3, ref: 'zn-elephant', select: 1},
    ],
  },
  {
    id: 'bio-drylands-mountains', 
    name: "txt-bio-drylands-mountains-name",
    flags: '+dry +mountain',
    debugColor: 'brown',
    eventImg: {
      day:'evt_bio_drylands_1.png', 
      night:'evt_bio_drylands_1_night.png'
    },
    terrain: [
      {perlin: 0.80,  tile: 'tl-dry'},
      {perlin: 0.75,  tile: 'tl-mountain'},
      {perlin: 0.73,  tile: 'tl-dry'},
      {perlin: 0.72,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.70,  tile: 'tl-mountain'},
      {perlin: 0.65,  tile: 'tl-dry'},
      {perlin: 0.63,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.60,  tile: 'tl-dry-jungle-light'},
      {perlin: 0.59,  tile: 'tl-hill'},
      {perlin: 0.54,  tile: 'tl-mountain'},
      {perlin: 0.53,  tile: 'tl-hill'},
      {perlin: 0.50,  tile: 'tl-mountain'},
      {perlin: 0.45,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.42,  tile: 'tl-dry'},
      {perlin: 0.40,  tile: 'tl-mountain'},
      {perlin: 0.38,  tile: 'tl-dry-jungle-light'},
      {perlin: 0.35,  tile: 'tl-hill'},
      {perlin: 0.32,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.31,  tile: 'tl-hill'},
      {perlin: 0.30,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.27,  tile: 'tl-dry-jungle-light'},
      {perlin: 0.20,  tile: 'tl-mountain'},
      {perlin: 0.15,  tile: 'tl-dry'},
      {perlin: 0.10,  tile: 'tl-mountain'},
      {perlin: 0.00,  tile: 'tl-dry'},
    ],
    fixtures: [
      // {select: 1, group: 'grp-rest'},
      // {select: 2, group: 'grp-cave'},
      // {select: 1, group: 'grp-treasure'},
      // {select: 1, group: 'grp-eyeCandy-drylands'},
    ],
    zones: [
      {chance: 1.0, select: 1, group: [
        {slots: 1, ref: 'zn-hyena'},
        {slots: 3, ref: 'zn-panther'},
        {slots: 1, ref: 'zn-gorilla'},
      ]},
      {chance: 0.3, select: 1, group: [
        {slots: 3, ref: 'zn-panther'},
      ]},
      {reqWorld: [2,3], chance: 1.0, select: 1, group: [
        {slots: 1, ref: 'zn-tiger'},
        {slots: 2, ref: 'zn-panther'},
        {slots: 1, ref: 'zn-gorilla'},
        {slots: 3, ref: 'zn-giantBird'},
        {slots: 1, ref: 'zn-giantCrab'},
      ]},
      {reqWorld: [4,5], chance: 1.0, select: 1, group: [
        {slots: 1, ref: 'zn-tiger'},
        {slots: 2, ref: 'zn-panther'},
        {slots: 1, ref: 'zn-gorilla'},
        {slots: 2, ref: 'zn-giantBird'},
        {slots: 2, ref: 'zn-raptor'},
      ]},

      {chance: 0.3, ref: 'zn-elephant', select: 1},
    ],
  },
  {
    id: 'bio-drylands-jungle', 
    name: "txt-bio-drylands-jungle-name",
    flags: '+dry',
    debugColor: 'brown',
    eventImg: {
      day:'evt_bio_drylands_1.png', 
      night:'evt_bio_drylands_1_night.png'
    },
    terrain: [
      {perlin: 0.86,  tile: 'tl-mountain'},
      {perlin: 0.84,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.80,  tile: 'tl-dry'},
      {perlin: 0.77,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.76,  tile: 'tl-hill'},
      {perlin: 0.75,  tile: 'tl-dry-jungle-light'},
      {perlin: 0.74,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.73,  tile: 'tl-dry-jungle-light'},
      {perlin: 0.72,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.70,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.66,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.65,  tile: 'tl-mountain'},
      {perlin: 0.63,  tile: 'tl-dry-jungle-light'},
      {perlin: 0.62,  tile: 'tl-dry'},
      {perlin: 0.61,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.58,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.57,  tile: 'tl-dry-jungle-light'},
      {perlin: 0.55,  tile: 'tl-dry'},
      {perlin: 0.53,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.52,  tile: 'tl-hill'},
      {perlin: 0.51,  tile: 'tl-dry'},
      {perlin: 0.49,  tile: 'tl-dry-jungle-light'},
      {perlin: 0.45,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.43,  tile: 'tl-dry'},
      {perlin: 0.42,  tile: 'tl-hill'},
      {perlin: 0.39,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.38,  tile: 'tl-hill'},
      {perlin: 0.34,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.30,  tile: 'tl-dry-jungle-light'},
      {perlin: 0.28,  tile: 'tl-dry'},
      {perlin: 0.27,  tile: 'tl-mountain'},
      {perlin: 0.20,  tile: 'tl-river'},
      {perlin: 0.19,  tile: 'tl-river-shallow'},
      {perlin: 0.18,  tile: 'tl-hill'},
      {perlin: 0.12,  tile: 'tl-river'},
      {perlin: 0.11,  tile: 'tl-hill'},
      {perlin: 0.10,  tile: 'tl-river-shallow'},
      {perlin: 0.05,  tile: 'tl-river'},
      {perlin: 0.00,  tile: 'tl-river-shallow'}
    ],
    fixtures: [
      // {select: 1, group: 'grp-rest'},
      // {select: 1, group: 'grp-treasure'},
      // {select: 1, group: 'grp-loot'},
      // {select: 1, group: 'grp-eyeCandy-drylands'},
    ],
    zones: [
      {chance: 1.0, select: 1, group: [
        {slots: 1, ref: 'zn-tiger'},
        {slots: 1, ref: 'zn-panther'},
        {slots: 1, ref: 'zn-gorilla'},
      ]},
      {chance: 0.3, select: 1, group: [
        {slots: 1, ref: 'zn-gorilla'},
        {slots: 1, ref: 'zn-tiger'},
      ]},
      {reqWorld: [2,3], chance: 1.0, select: 1, group: [
        {slots: 1, ref: 'zn-tiger'},
        {slots: 2, ref: 'zn-panther'},
        {slots: 1, ref: 'zn-gorilla'},
        {slots: 1, ref: 'zn-crocodile'},
        {slots: 3, ref: 'zn-giantBird'},
        {slots: 1, ref: 'zn-giantCrab'},
        {slots: 1, ref: 'zn-zombiePygmy'},
      ]},
      {reqWorld: [4,5], chance: 1.0, select: 1, group: [
        {slots: 1, ref: 'zn-tiger'},
        {slots: 2, ref: 'zn-panther'},
        {slots: 1, ref: 'zn-gorilla'},
        {slots: 2, ref: 'zn-giantBird'},
        {slots: 2, ref: 'zn-raptor'},
        {slots: 2, ref: 'zn-zombiePygmy'},
      ]},

      {chance: 0.3, ref: 'zn-elephant', select: 1},
    ],
  },
  {
    id: 'bio-drylands-desert', 
    name: "txt-pck-dry-name",
    flags: '+dry +desert',
    debugColor: 'brown',
    eventImg: {
      day:'evt_bio_drylands_1.png', 
      night:'evt_bio_drylands_1_night.png'
    },
    terrain: [
      {perlin: 0.90, tile: 'tl-mountain'},
      {perlin: 0.86, tile: 'tl-desert'},
      {perlin: 0.81, tile: 'tl-dry'},
      {perlin: 0.79, tile: 'tl-mountain'},
      {perlin: 0.78, tile: 'tl-volcano-inactive'},
      {perlin: 0.77, tile: 'tl-mountain'},
      {perlin: 0.75, tile: 'tl-hill'},
      {perlin: 0.73, tile: 'tl-dry'},
      {perlin: 0.66, tile: 'tl-desert'},
      {perlin: 0.65, tile: 'tl-dry'},
      {perlin: 0.63, tile: 'tl-cactusForest'},
      {perlin: 0.59, tile: 'tl-desert'},
      {perlin: 0.58, tile: 'tl-cactusForest'},
      {perlin: 0.52, tile: 'tl-dry'},
      {perlin: 0.50, tile: 'tl-dry-stoneForest'},
      {perlin: 0.47, tile: 'tl-dry'},
      {perlin: 0.43, tile: 'tl-mountain'},
      {perlin: 0.41, tile: 'tl-hill'},
      {perlin: 0.38, tile: 'tl-desert'},
      {perlin: 0.35, tile: 'tl-dry'},
      {perlin: 0.33, tile: 'tl-desert'},
      {perlin: 0.29, tile: 'tl-mountain'},
      {perlin: 0.26, tile: 'tl-desert'},
      {perlin: 0.24, tile: 'tl-dry'},
      {perlin: 0.21, tile: 'tl-desert'},
      {perlin: 0.17, tile: 'tl-dry'},
      {perlin: 0.15, tile: 'tl-desert'},
      {perlin: 0.13, tile: 'tl-cactusForest'},
      {perlin: 0.00, tile: 'tl-mountain'},
    ],
    fixtures: [
      // {select: 1, group: 'grp-rest'},
      // {select: 1, group: 'grp-treasure'},
      // {select: 1, group: [
      //   {slots: 1, group: 'grp-utility'},
      //   {slots: 1, group: 'grp-loot'},
      // ]},
      // {select: 1, group: 'grp-eyeCandy-drylands'},
    ],
    zones: [
      {chance: 1.0, select: 1, group: [
        {slots: 1, ref: 'zn-tiger'},
        {slots: 1, ref: 'zn-hyena'},
      ]},
      {chance: 0.3, select: 1, group: [
        {slots: 1, ref: 'zn-giantScorpion'},
      ]},
      {reqWorld: [2,3], chance: 1.0, select: 1, group: [
        {slots: 1, ref: 'zn-panther'},
        {slots: 3, ref: 'zn-giantBird'},
        {slots: 3, ref: 'zn-giantScorpion'},
      ]},
      {reqWorld: [4,5], chance: 1.0, select: 1, group: [,
        {slots: 1, ref: 'zn-panther'},
        {slots: 2, ref: 'zn-giantBird'},
        {slots: 1, ref: 'zn-raptor'},
        {slots: 3, ref: 'zn-giantScorpion'},
      ]},

      {chance: 0.3, ref: 'zn-elephant', select: 1},
    ],
  },
  {
    id: 'bio-drylands-pits',
    name: "txt-bio-drylands-pits-name",
    flags: '+dry +pits',
    debugColor: 'brown',
    eventImg: {
      day:'evt_bio_drylands_1.png',
      night:'evt_bio_drylands_1_night.png'
    },
    terrain: [
      {perlin: 0.76,  tile: 'tl-pit-dry'},
      {perlin: 0.73,  tile: 'tl-dry'},
      {perlin: 0.71,  tile: 'tl-pit-dry'},
      {perlin: 0.68,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.65,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.60,  tile: 'tl-mountain'},
      {perlin: 0.55,  tile: 'tl-dry-jungle-light'},
      {perlin: 0.53,  tile: 'tl-pit-dry'},
      {perlin: 0.51,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.49,  tile: 'tl-pit-dry'},
      {perlin: 0.47,  tile: 'tl-dry'},
      {perlin: 0.45,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.43,  tile: 'tl-dry'},
      {perlin: 0.42,  tile: 'tl-hill'},
      {perlin: 0.40,  tile: 'tl-mountain'},
      {perlin: 0.39,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.38,  tile: 'tl-dry-jungle-light'},
      {perlin: 0.37,  tile: 'tl-dry'},
      {perlin: 0.36,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.355, tile: 'tl-hill'},
      {perlin: 0.34,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.31,  tile: 'tl-dry'},
      {perlin: 0.00,  tile: 'tl-pit-dry'},
    ],
    fixtures: [
      // {select: 1, group: 'grp-rest'},
      // {select: 1, group: 'grp-cave'},
      // {select: 1, group: 'grp-treasure'},
      // {select: 1, group: [
      //   {slots: 1, group: 'grp-utility'},
      //   {slots: 3, group: 'grp-sacrileg'},
      // ]},
      // {select: 1, group: 'grp-eyeCandy-drylands'},
    ],
    zones: [
      {chance: 1.0, select: 1, group: [
        {slots: 1, ref: 'zn-tiger'},
        {slots: 1, ref: 'zn-gorilla'},
        {slots: 1, ref: 'zn-panther'},
        {slots: 1, ref: 'zn-hyena'},
      ]},
      {chance: 0.3, select: 1, group: [
        {slots: 1, ref: 'zn-tiger'},
      ]},
      {reqWorld: [2,3], chance: 1.0, select: 1, group: [
        {slots: 1, ref: 'zn-panther'},
        {slots: 3, ref: 'zn-giantBird'},
        {slots: 1, ref: 'zn-gorilla'},
        {slots: 1, ref: 'zn-tiger'},
        {slots: 3, ref: 'zn-raptor'},
      ]},
      {reqWorld: [4,5], chance: 1.0, select: 1, group: [,
        {slots: 1, ref: 'zn-panther'},
        {slots: 1, ref: 'zn-gorilla'},
        {slots: 1, ref: 'zn-tiger'},
        {slots: 3, ref: 'zn-giantBird'},
        {slots: 3, ref: 'zn-raptor'},
      ]},

      {chance: 0.3, ref: 'zn-elephant', select: 1},
    ],
  },
  {
    id: 'bio-drylands-stoneForest',
    name: "txt-bio-drylands-stoneForest-name",
    flags: '+dry',
    debugColor: 'brown',
    eventImg: {
      day:'evt_bio_drylands_1.png',
      night:'evt_bio_drylands_1_night.png'
    },
    terrain: [
      {perlin: 0.76,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.74,  tile: 'tl-dry'},
      {perlin: 0.68,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.65,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.60,  tile: 'tl-mountain'},
      {perlin: 0.55,  tile: 'tl-dry-jungle-light'},
      {perlin: 0.50,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.44,  tile: 'tl-dry'},
      {perlin: 0.42,  tile: 'tl-hill'},
      {perlin: 0.40,  tile: 'tl-mountain'},
      {perlin: 0.36,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.34,  tile: 'tl-hill'},
      {perlin: 0.33,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.31,  tile: 'tl-dry'},
      {perlin: 0.00,  tile: 'tl-dry-stoneForest'},
    ],
    fixtures: [
      // {select: 1, group: 'grp-rest'},
      // {select: 1, group: 'grp-treasure'},
      // {select: 1, group: [
      //   {slots: 1, ref: 'fxt-stoneCircle-1'},
      //   {slots: 1, ref: 'fxt-shamanHut'},
      //   {slots: 2, group: 'grp-loot'},
      // ]},
    ],
    zones: [
      {chance: 1.0, select: 1, group: [
        {slots: 1, ref: 'zn-tiger'},
        {slots: 1, ref: 'zn-panther'},
        {slots: 1, ref: 'zn-hyena'},
      ]},
      {chance: 0.3, select: 1, group: [
        {slots: 1, ref: 'zn-raptor'},
      ]},
      {reqWorld: [2,3], chance: 1.0, select: 1, group: [
        {slots: 1, ref: 'zn-panther'},
        {slots: 1, ref: 'zn-tiger'},
        {slots: 2, ref: 'zn-giantBird'},
        {slots: 1, ref: 'zn-gorilla'},
        {slots: 1, ref: 'zn-tiger'},
        {slots: 3, ref: 'zn-raptor'},
        {slots: 1, ref: 'zn-giantScorpion'},
      ]},
      {reqWorld: [4,5], chance: 1.0, select: 1, group: [,
        {slots: 1, ref: 'zn-panther'},
        {slots: 1, ref: 'zn-tiger'},
        {slots: 3, ref: 'zn-giantBird'},
        {slots: 1, ref: 'zn-gorilla'},
        {slots: 1, ref: 'zn-tiger'},
        {slots: 4, ref: 'zn-raptor'},
        {slots: 3, ref: 'zn-giantScorpion'},
        {slots: 3, ref: 'zn-zombiePygmy'},
      ]},

      {chance: 0.3, ref: 'zn-elephant', select: 1},
    ],
  },

])