config.entities.add([

// pockets

  {
    id: 'pck-prehistoric', 
    name: "txt-pck-prehistoric-name",
    flags: '+fantastic +prehistoric',
    borderBiome: ['bio-outside-sea'],
    previewSprite: 'hud_worldmap_pocketPreview_mushrooms.png',
    slotMarker: 'hud_mapMarker_grass.png',
    description: "txt-pck-prehistoric",
    ambientSound: 'sfx_loop_prehistoric_1',
    goals: [
      'gol-goldenTemple-buried'
    ],
    fixtures: [
      {reqWorld: '2..', reqDifficulty: '2', select: 1, ref: 'fxt-magneticMountain'},
      {reqWorld: '3..', reqDifficulty: '1..', select: 1, ref: 'fxt-magneticMountain'},
      {reqWorld: '4..', reqDifficulty: '1..', select: 1, ref: 'fxt-magneticMountain'},

      {reqWorld: '3..', select: 2, ref: 'fxt-cave-teleport'},

      {reqWorld: '3', select: 2, ref: 'fxt-volcano-spawn-small-inactive'},
      {reqWorld: '4', select: 2, group: [
        {slots: 2, select:3, ref: 'fxt-volcano-spawn-small-inactive'},
        {slots: 2, select:2, ref: 'fxt-volcano-spawn-small-inactive'},
        {slots: 2, select:1, ref: 'fxt-volcano-spawn-large-inactive'},
      ]},
      {reqWorld: '5', select: 2, group: [
        {slots: 2, select:6, ref: 'fxt-volcano-spawn-small-inactive'},
        {slots: 2, select:3, ref: 'fxt-volcano-spawn-small-inactive'},
        {slots: 2, select:2, ref: 'fxt-volcano-spawn-large-inactive'},
        {slots: 2, select:2, ref: 'fxt-volcano-spawn-large-inactive'},
      ]},
    ],
    biomes: [
      //{ref: 'bio-prehistoric-chasm', /*reqWorld:'..6'*/}, Not ready yet
      {ref: 'bio-prehistoric-generic'},
      {select:2, group: 'grp-prehistoric-sanity'},
      {select:1, group: 'grp-prehistoric-sanity', reqDifficulty: '0'},
      {select:3, group: 'grp-prehistoric-noSanity'},

    ],
  }, 

  // biome groups

    {
      id: 'grp-prehistoric-sanity',
      group: [
        {slots: 1, ref: 'bio-prehistoric-generic'},
        {slots: 1, ref: 'bio-prehistoric-mountains'},
        {slots: 2, ref: 'bio-prehistoric-mushrooms'},
      ]
    },
    {
      id: 'grp-prehistoric-noSanity',
      group: [
        {slots: 1, ref: 'bio-prehistoric-stoneForest'},
        {slots: 1, ref: 'bio-prehistoric-dry'},
      ]
    },

// biomes

  {
    id: 'bio-prehistoric-generic', 
    name: "txt-bio-warped-prehistoric-name",
    flags: {prehistoric:true, grass:true},
    eventImg: {day:'evt_bio_prehistoric_1.png', night:'evt_bio_prehistoric_1_night.png'},
    terrain: [
      {perlin: 0.80,  tile: 'tl-dry'},
      {perlin: 0.74,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.72,  tile: 'tl-mountain'},
      {perlin: 0.70,  tile: 'tl-volcano-inactive'},
      {perlin: 0.66,  tile: 'tl-mountain'},
      {perlin: 0.61,  tile: 'tl-jungle-thick'},
      {perlin: 0.60,  tile: 'tl-volcano-inactive'},
      {perlin: 0.585, tile: 'tl-dry-stoneForest'},
      {perlin: 0.55,  tile: 'tl-jungle-thick'},
      {perlin: 0.54,  tile: 'tl-jungle-light'},
      {perlin: 0.50,  tile: 'tl-grass'},
      {perlin: 0.498, tile: 'tl-giantMushrooms'},
      {perlin: 0.45,  tile: 'tl-grass'},
      {perlin: 0.44,  tile: 'tl-grass-bushes'},
      {perlin: 0.30,  tile: 'tl-grass'},
      {perlin: 0.23,  tile: 'tl-jungle-thick'},
      {perlin: 0.21,  tile: 'tl-sulfur-swamp'},
      {perlin: 0.20,  tile: 'tl-sulfur-shallow'},
      {perlin: 0.16,  tile: 'tl-sulfur'},
      {perlin: 0.13,  tile: 'tl-sulfur-shallow'},
      {perlin: 0.11,  tile: 'tl-sulfur'},
      {perlin: 0.1,   tile: 'tl-sulfur-shallow'},
      {perlin: 0.0,   tile: 'tl-sulfur'},
    ],
    fixtures: [
      {select: 1, group: 'grp-village-fantastic'},
      {select: 1, group: 'grp-sacrileg'},
      {select: 1, group: [
        {slots: 1, group: 'grp-utility'},
        {slots: 1, group: 'grp-loot'},
      ]},
    ],
    zones: [
      {chance: 1.0, select: 1, group: [
        {slots: 3, ref: 'zn-sabertooth'},
        {slots: 3, ref: 'zn-raptor'},
        {slots: 3, ref: 'zn-giantBird'},
        {slots: 1, ref: 'zn-giantCrab'},
        {slots: 1, ref: 'zn-giantScorpion'},
      ]},
      {chance: 0.3, select: 1, group: [
        {slots: 1, ref: 'zn-raptor'},
      ]},
      {reqWorld: [4], chance: 1.0, select: 1, group: [
        {slots: 2, ref: 'zn-giantBird'},
        {slots: 3, ref: 'zn-sabertooth'},
        {slots: 3, ref: 'zn-raptor'},
        {slots: 2, ref: 'zn-giantCrab'},
        {slots: 1, ref: 'zn-zombiePygmy'},
        {slots: 1, ref: 'zn-giantScorpion'},
      ]},
      {reqWorld: [5], chance: 1.0, select: 1, group: [
        {slots: 3, ref: 'zn-sabertooth'},
        {slots: 3, ref: 'zn-giantBird'},
        {slots: 3, ref: 'zn-raptor'},
        {slots: 3, ref: 'zn-raptor'},
        {slots: 2, ref: 'zn-giantCrab'},
        {slots: 2, ref: 'zn-zombiePygmy'},
        {slots: 1, ref: 'zn-giantScorpion'},
      ]},
    ],
  },
  {
    id: 'bio-prehistoric-chasm', 
    extends: 'bio-prehistoric-generic',
    name: "txt-bio-warped-prehistoric-name",
    flags: {prehistoric:true, grass:true},
    terrain: [
      {perlin: 0.53,   tile: 'tl-grass'},
      {perlin: 0.50,   tile: 'tl-grass-stoneForest'},
      {perlin: 0.48,   tile: 'tl-dry'},
      {perlin: 0.46,   tile: 'tl-grass'},
      {perlin: 0.40,   tile: 'tl-giantMushrooms'},
      {perlin: 0.35,   tile: 'tl-river-shallow'},
      {perlin: 0.30,   tile: 'tl-jungle-light'},
      {perlin: 0.20,   tile: 'tl-jungle-thick'},
      {perlin: 0.10,   tile: 'tl-grass-stoneForest'},
      {perlin: 0.00,   tile: 'tl-grass'},
    ],
    fixtures: [
      {chance: 1.0, select: 3, ref: 'fxt-special-chasmCircle'},
    ],
  },
  {
    id: 'bio-prehistoric-mountains', 
    extends: 'bio-prehistoric-generic',
    name: "txt-bio-warped-prehistoric-name",
    flags: {prehistoric:true, mountains:true},
    terrain: [
      {perlin: 0.85,  tile: 'tl-mountain'},
      {perlin: 0.74,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.72,  tile: 'tl-mountain'},
      {perlin: 0.70,  tile: 'tl-volcano-inactive'},
      {perlin: 0.65,  tile: 'tl-grass'},
      {perlin: 0.64,  tile: 'tl-volcano-inactive'},
      {perlin: 0.62,  tile: 'tl-mountain'},
      {perlin: 0.61,  tile: 'tl-volcano-inactive'},
      {perlin: 0.585, tile: 'tl-dry-stoneForest'},
      {perlin: 0.52,  tile: 'tl-giantMushrooms'},
      {perlin: 0.51,  tile: 'tl-volcano-inactive'},
      {perlin: 0.50,  tile: 'tl-grass-stoneForest'},
      {perlin: 0.498, tile: 'tl-volcano-inactive'},
      {perlin: 0.45,  tile: 'tl-grass'},
      {perlin: 0.44,  tile: 'tl-grass-bushes'},
      {perlin: 0.38,  tile: 'tl-grass'},
      {perlin: 0.35,  tile: 'tl-volcano-inactive'},
      {perlin: 0.30,  tile: 'tl-grass-stoneForest'},
      {perlin: 0.23,  tile: 'tl-jungle-thick'},
      {perlin: 0.17,  tile: 'tl-volcano-inactive'},
      {perlin: 0.13,  tile: 'tl-grass-stoneForest'},
      {perlin: 0.1,   tile: 'tl-grass-stoneForest'},
      {perlin: 0.0,   tile: 'tl-mountain'},
    ],
    fixtures: [
      {select: 1, group: 'grp-sanity-nature'},
      {select: 1, group: 'grp-cave'},
      {select: 1, group: 'grp-cave'},
    ],
  },
  {
    id: 'bio-prehistoric-stoneForest', 
    extends: 'bio-prehistoric-generic',
    name: "txt-bio-warped-prehistoric-name",
    flags: {prehistoric:true, grass:true},
    terrain: [
      {perlin: 0.74,  tile: 'tl-grass-stoneForest'},
      {perlin: 0.72,  tile: 'tl-mountain'},
      {perlin: 0.70,  tile: 'tl-volcano-inactive'},
      {perlin: 0.66,  tile: 'tl-mountain'},
      {perlin: 0.61,  tile: 'tl-jungle-thick'},
      {perlin: 0.60,  tile: 'tl-volcano-inactive'},
      {perlin: 0.585, tile: 'tl-grass-stoneForest'},
      {perlin: 0.55,  tile: 'tl-jungle-thick'},
      {perlin: 0.54,  tile: 'tl-jungle-light'},
      {perlin: 0.50,  tile: 'tl-grass'},
      {perlin: 0.498, tile: 'tl-giantMushrooms'},
      {perlin: 0.45,  tile: 'tl-grass'},
      {perlin: 0.44,  tile: 'tl-grass-bushes'},
      {perlin: 0.23,  tile: 'tl-grass-stoneForest'},
      {perlin: 0.21,  tile: 'tl-sulfur-swamp'},
      {perlin: 0.20,  tile: 'tl-sulfur-shallow'},
      {perlin: 0.16,  tile: 'tl-sulfur'},
      {perlin: 0.13,  tile: 'tl-sulfur-shallow'},
      {perlin: 0.11,  tile: 'tl-sulfur'},
      {perlin: 0.1,   tile: 'tl-sulfur-shallow'},
      {perlin: 0.0,   tile: 'tl-sulfur'},
    ],
    fixtures: [
      {select: 1, group: 'grp-treasure'},
      {select: 1, group: 'grp-monsterDen'},
      {select: 1, group: [
        {slots: 1, group: 'grp-utility'},
        {slots: 1, group: 'grp-cave'},
        {slots: 1, group: 'grp-sacrileg'},
      ]},
    ],
  },
  {
    id: 'bio-prehistoric-dry', 
    extends: 'bio-prehistoric-generic',
    name: "txt-bio-warped-prehistoric-name",
    flags: {desert:true, prehistoric:true},
    terrain: [
      {perlin: 0.89,  tile: 'tl-jungle-thick'},
      {perlin: 0.80,  tile: 'tl-dry'},
      {perlin: 0.74,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.72,  tile: 'tl-mountain'},
      {perlin: 0.70,  tile: 'tl-volcano-inactive'},
      {perlin: 0.66,  tile: 'tl-mountain'},
      {perlin: 0.61,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.60,  tile: 'tl-volcano-inactive'},
      {perlin: 0.585, tile: 'tl-dry-stoneForest'},
      {perlin: 0.55,  tile: 'tl-dry-jungle-thick'},
      {perlin: 0.54,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.50,  tile: 'tl-dry'},
      {perlin: 0.498, tile: 'tl-hill'},
      {perlin: 0.45,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.44,  tile: 'tl-dry'},
      {perlin: 0.30,  tile: 'tl-desert'},
      {perlin: 0.23,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.20,  tile: 'tl-dry'},
      {perlin: 0.17,  tile: 'tl-mountain'},
      {perlin: 0.0,   tile: 'tl-desert'},
    ],
    fixtures: [
      {select: 1, group: 'grp-treasure'},
      {select: 1, group: 'grp-cave'},
      {select: 1, group: 'grp-utility'},
    ],
  },
  {
    id: 'bio-prehistoric-mushrooms', 
    extends: 'bio-prehistoric-generic',
    name: "txt-bio-warped-prehistoric-name",
    flags: {prehistoric:true, mushrooms:true},
    terrain: [
      {perlin: 0.85,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.74,  tile: 'tl-grass'},
      {perlin: 0.66,  tile: 'tl-volcano-inactive'},
      {perlin: 0.60,  tile: 'tl-giantMushrooms'},
      {perlin: 0.57,  tile: 'tl-jungle-thick'},
      {perlin: 0.56,  tile: 'tl-jungle-light'},
      {perlin: 0.55,  tile: 'tl-river-shallow'},
      {perlin: 0.51,  tile: 'tl-river'},
      {perlin: 0.5,   tile: 'tl-river-shallow'},
      {perlin: 0.485, tile: 'tl-jungle-thick'},
      {perlin: 0.48,  tile: 'tl-hill'},
      {perlin: 0.45,  tile: 'tl-giantMushrooms'},
      {perlin: 0.41,  tile: 'tl-jungle-thick'},
      {perlin: 0.35,  tile: 'tl-grass'},
      {perlin: 0.34,  tile: 'tl-grass-bushes'},
      {perlin: 0.31,  tile: 'tl-giantMushrooms'},
      {perlin: 0.20,  tile: 'tl-grass'},
      {perlin: 0.17,  tile: 'tl-dry-stoneForest'},
      {perlin: 0.16,  tile: 'tl-grass-bushes'},
      {perlin: 0.15,  tile: 'tl-swamp'},
      {perlin: 0.14,  tile: 'tl-sulfur-shallow'},
      {perlin: 0.11,  tile: 'tl-sulfur'},
      {perlin: 0.1,   tile: 'tl-sulfur-shallow'},
      {perlin: 0.0,   tile: 'tl-sulfur'},
    ],
    fixtures: [
      {select: 1, group: 'grp-sanity-nature'},
      {select: 1, group: 'grp-cave'},
      {select: 1, group: 'grp-monsterDen'},
    ],
  },
])