config.entities.add([

  {
    id: 'it-pelt-hyena',
    name: "txt-it-pelt-hyena-name",
    description: "txt-it-pelt-hyena",
    debugCategory: 'trophy',
    sprite: 'it_animal_pelthyena_1.png',
    value: {
      base: 15,
      trader: 20,
      karma: 1,
    },
    maxStack: 10,
    fame: fameVeryTiny,
    funds: fundsTiny,
  },
  {
    id: 'it-pelt-tiger',
    name: "txt-it-pelt-tiger-name",
    description: "txt-it-pelt-tiger",
    debugCategory: 'trophy',
    sprite: 'it_animal_pelttiger_1.png',
    value: {
      base: 20,
      trader: 35,
      karma: 1,
    },
    maxStack: 10,
    fame: fameTiny,
    funds: fundsSmall,
  },
  {
    id: 'it-pelt-tiger-white',
    name: "txt-it-pelt-tiger-white-name",
    description: "txt-it-pelt-tiger-white",
    debugCategory: 'trophy',
    sprite: 'it_animal_peltwhitetiger_1.png',
    value: {
      base: 20,
      trader: 50,
      karma: 1,
    },
    maxStack: 10,
    fame: fameLarge,
    funds: fundsLarge,
  },
  {
    id: 'it-pelt-sabertooth',
    name: "txt-it-pelt-sabertooth-name",
    description: "txt-it-pelt-sabertooth",
    debugCategory: 'trophy',
    sprite: 'it_animal_peltsabertooth_1.png',
    value: {
      base: 30,
      trader: 45,
      karma: 1,
    },
    maxStack: 10,
    fame: fameSmall,
    funds: fundsMedium,
  },
  {
    id: 'it-pelt-sabertooth-white',
    sprite: 'it_animal_peltsabertooth_white.png',
    extends: 'it-pelt-sabertooth',
  },
  {
    id: 'it-pelt-polarBear',
    name: "txt-it-pelt-polarBear-name",
    description: "txt-it-pelt-polarBear",
    debugCategory: 'trophy',
    sprite: 'it_animal_peltpolarBear_1.png',
    value: {
      base: 20,
      trader: 40,
      karma: 1,
    },
    maxStack: 10,
    fame: fameSmall,
    funds: fundsMedium,
  },
  {
    id: 'it-pelt-arctic-wolf',
    name: "txt-it-pelt-arctic-wolf-name",
    description: "txt-it-pelt-arctic-wolf",
    debugCategory: 'trophy',
    sprite: 'it_animal_peltpolarBear_1.png',
    value: {
      base: 15,
      trader: 35,
      karma: 1,
    },
    maxStack: 10,
    fame: fameTiny,
    funds: fundsSmall,
  },
  {
    id: 'it-pelt-panther',
    name: "txt-it-pelt-panther-name",
    description: "txt-it-pelt-panther",
    debugCategory: 'trophy',
    sprite: 'it_animal_peltpanther_1.png',
    value: {
      base: 20,
      trader: 35,
      karma: 1,
    },
    maxStack: 10,
    fame: fameTiny,
    funds: fundsSmall,
  },
  {
    id: 'it-pelt-crocodile',
    name: "txt-it-pelt-crocodile-name",
    description: "txt-it-pelt-crocodile",
    debugCategory: 'trophy',
    sprite: 'it_animal_skincrocodile_1.png',
    value: {
      base: 20,
      trader: 50,
      karma: 1,
    },
    maxStack: 10,
    fame: fameTiny,
    funds: fundsMedium,
  },

  {
    id: 'it-animalTooth',
    name: "txt-it-animalTooth-name",
    description: "txt-it-animalTooth",
    debugCategory: 'trophy',
    sprite: 'it_animal_tooth_1.png',
    value: {
      base: 10,
      trader: 15,
    },
    noWeight: true,
    maxStack: 20,
    fame: fameVeryTiny,
    funds: fundsTiny,
  },
  {
    id: 'it-sabertooth',
    name: "txt-it-sabertooth-name",
    description: "txt-it-sabertooth",
    debugCategory: 'trophy',
    sprite: 'it_animal_sabertooth_1.png',
    value: {
       base: 30,
      trader: 40,
    },
    maxStack: 10,
    fame: fameSmall,
    funds: fundsMedium,
  },
  {
    id: 'it-walrustooth',
    name: "txt-it-walrustooth-name",
    description: "txt-it-walrustooth",
    debugCategory: 'trophy',
    sprite: 'it_animal_sabertooth_1.png',
    value: {
       base: 20,
      trader: 30,
    },
    maxStack: 10,
    fame: fameSmall,
    funds: fundsSmall,
  },
  {
    id: 'it-gorillaPaw',
    name: "txt-it-gorillaPaw-name",
    description: "txt-it-gorillaPaw",
    debugCategory: 'trophy',
    sprite: 'it_animal_gorillapaw_1.png',
    value: {
      base: 20,
      trader: 35,
    },
    maxStack: 10,
    fame: fameVeryTiny,
    funds: fundsSmall,
  },
  {
    id: 'it-yetiPaw',
    name: "txt-it-yetiPaw-name",
    description: "txt-it-yetiPaw",
    debugCategory: 'trophy',
    sprite: 'it_animal_yetipaw_1.png',
    value: {
      base: 30,
      trader: 45,
    },
    maxStack: 10,
    fame: fameLarge,
    funds: fundsMedium,
  },
  {
    id: 'it-spiderLeg',
    name: "txt-it-spiderLeg-name",
    description: "txt-it-spiderLeg",
    debugCategory: 'trophy',
    sprite: 'it_animal_spiderLeg_1.png',
    value: {
      base: 10,
      trader: 25,
    },
    maxStack: 10,
    fame: fameTiny,
    funds: fundsSmall,
  },
  {
    id: 'it-giantCrabPincer',
    name: "txt-it-giantCrabPincer-name",
    description: "txt-it-giantCrabPincer",
    debugCategory: 'trophy',
    sprite: 'it_animal_pincer_1.png',
    value: {
      base: 30,
      trader: 60,
      karma: 1,
    },
    maxStack: 5,
    fame: fameSmall,
    funds: fundsSmall,
  },
  {
    id: 'it-giantScorpionSting',
    name: "txt-it-giantScorpionSting-name",
    description: "txt-it-giantScorpionSting",
    debugCategory: 'trophy',
    sprite: 'it_animal_sting_1.png',
    value: {
      base: 30,
      trader: 60,
      karma: 1,
    },
    maxStack: 5,
    fame: fameSmall,
    funds: fundsSmall,
  },
  {
    id: 'it-giantBirdFeather',
    name: "txt-it-giantBirdFeather-name",
    description: "txt-it-giantBirdFeather",
    debugCategory: 'trophy',
    sprite: 'it_animal_feather_1.png',
    value: {
      base: 30,
      trader: 60,
      karma: 1,
    },
    maxStack: 20,
    fame: fameVerySmall,
    funds: fundsSmall,
  },
  // {
  //   id: 'it-raptorTooth',
  //   name: "A raptor's tooth",
  //   description: "A raptor incisor. Good for trading.",
  //   debugCategory: 'trophy',
  //   sprite: 'it_animal_tooth_1.png',
  //   maxStack: 20,
  //   value: {
  //     base: 30,
  //     trader: 50,
  //     karma: karmaMedium,
  //   },
  //   fame: fameVerySmall,
  //   funds: fundsSmall,
  // },
  {
    id: 'it-raptorScale',
    name: "txt-it-raptorScale-name",
    description: "txt-it-raptorScale",
    debugCategory: 'trophy',
    sprite: 'it_animal_skinraptor_1.png',
    value: {
      base: 30,
      trader: 50,
      karma: 1,
    },
    maxStack: 20,
    fame: fameSmall,
    funds: fundsLarge,
  },

])